# Generated by Django 3.1.2 on 2020-10-08 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='sodu',
        ),
    ]
