# Generated by Django 3.1.2 on 2020-10-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20201009_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='address',
        ),
        migrations.AddField(
            model_name='myuser',
            name='sodu',
            field=models.IntegerField(default=0),
        ),
    ]
