# Generated by Django 3.1.2 on 2020-10-25 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_history'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='History',
            new_name='HistoryModel',
        ),
    ]
