# Generated by Django 3.1.2 on 2020-10-25 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20201025_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymodel',
            name='time_pub',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
