# Generated by Django 3.1.2 on 2020-10-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_historymodel_time_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymodel',
            name='so_luong',
            field=models.CharField(default='', max_length=9999),
        ),
    ]
