# Generated by Django 3.1.2 on 2020-10-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymodel',
            name='time_pub',
            field=models.DateTimeField(),
        ),
    ]
