# Generated by Django 3.1.2 on 2020-10-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20201025_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymodel',
            name='time_pub',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
