# Generated by Django 3.1.2 on 2020-10-25 14:20

from django.db import migrations, models
import django.utils.timezone
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20201025_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymodel',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name=login.models.MyUser),
            preserve_default=False,
        ),
    ]
