# Generated by Django 3.1.2 on 2020-10-25 14:27

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_historymodel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historymodel',
            name='title',
        ),
        migrations.AddField(
            model_name='historymodel',
            name='title_history',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name=django.contrib.auth.models.User),
            preserve_default=False,
        ),
    ]
