# Generated by Django 3.1.2 on 2020-10-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_auto_20201025_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymodel',
            name='list_clone',
            field=models.CharField(default='', max_length=9999),
        ),
    ]
